### ISSUE TITLE
Cannot install on NW 752 SP 04 because of ABAP_LANGUAGE_VERSION = 5

### ISSUE THREAD

**Issue by christianguenter2** [dominikpanzer/ABAP-Meterdata-Manager#1]
![grafik](https://user-images.githubusercontent.com/17437789/206203163-ac82e6f7-8fcc-4f38-9fdc-d491065eb2db.png)

https://github.com/dominikpanzer/ABAP-Meterdata-Manager/blob/43cb3660ab9f6c74c84dbe6e609ed1ea61092a7b/src/zeabl.tabl.xml#L14

I'd suggest to remove `ABAP_LANGUAGE_VERSION` as it shouldn't be dependent upon?

**Comment by dominikpanzer** [comment]
you are right. import via offline/ZIP should work as a temporary workaround. ... no it doesnt, it just skips the function group. great. I opened an issue for abapgit after talking to one of the abapgit-devs. this shouldnt happen.

**Comment by dominikpanzer** [comment]
Hey Christian, please check again if it works for you now.

**Comment by christianguenter2** [comment]
Thx. Works.
